import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';

const packageDir = new URL('..', import.meta.url);
const repoDir = new URL('../..', import.meta.url);

test('Rust-generated typed schema and TypeScript are clean', async () => {
  const schemaPath = new URL('schema/typed-request.schema.json', packageDir);
  const typedPath = new URL('src/typed.ts', packageDir);
  const beforeSchema = await readFile(schemaPath);
  const beforeTyped = await readFile(typedPath);
  const result = spawnSync('cargo', ['run', '-q', '-p', 'docxdriver-core', '--bin', 'generate_typed_schema'], {
    cwd: repoDir,
    encoding: 'utf8',
  });
  assert.equal(result.status, 0, result.stderr);
  assert.deepEqual(await readFile(schemaPath), beforeSchema, 'schema artifact drifted; regenerate and commit it');
  assert.deepEqual(await readFile(typedPath), beforeTyped, 'typed.ts drifted; regenerate and commit it');
  const schema = JSON.parse(beforeSchema);
  assert.ok(schema.$defs?.editOp, 'schema must expose stable $defs.editOp');
  assert.ok(schema.$defs?.CommandResult, 'schema must include CommandResult');
  assert.ok(schema.$defs?.PlanResult, 'schema must include PlanResult');
  const typed = beforeTyped.toString('utf8');
  assert.match(typed, /Generated by crates\/docxdriver-core\/src\/bin\/generate_typed_schema/);
});
