/** Generated by crates/docxdriver-core/src/bin/generate_typed_schema.rs. */
export type SourceHash = `sha256:${string}`;
export type ChangeMode = 'track' | 'direct';
export type ParagraphAddress = string;
export type InsertAnchor = string;
export type ChromeKind = 'default' | 'first' | 'even';
export type Point = number;
export type InsertPosition = 'before' | 'after';
export type LineSpacing = { mode: 'multiple'; value: number } | { mode: 'exact'; value: Point } | { mode: 'at_least'; value: Point };
export type EditOp =
  | { op: 'replace_equation'; at: ParagraphAddress; mathml: string; equation?: number; display?: boolean }
  | { op: 'delete_equation'; at: ParagraphAddress; equation?: number }
  | { op: 'replace_text'; at: ParagraphAddress; select: string; with: string; occurrence?: number }
  | { op: 'replace_paragraph'; at: ParagraphAddress; with: string }
  | { op: 'format_text'; at: ParagraphAddress; select: string; occurrence?: number; bold?: boolean; italic?: boolean; underline?: boolean; strike?: boolean; superscript?: boolean; subscript?: boolean; color?: string; font_size?: Point; clear?: string[] }
  | { op: 'format_paragraph'; at: ParagraphAddress; style?: string; alignment?: 'left'|'center'|'right'|'justify'; indent_left?: Point; indent_right?: Point; space_before?: Point; space_after?: Point; line_spacing?: LineSpacing; clear?: string[] }
  | { op: 'insert_paragraph'; at: InsertAnchor; position: InsertPosition; with?: string; style?: string; as?: string }
  | { op: 'delete_paragraphs'; at: ParagraphAddress[] }
  | { op: 'set_page_margins'; section?: number; top?: Point; right?: Point; bottom?: Point; left?: Point; header?: Point; footer?: Point; gutter?: Point }
  | { op: 'set_even_and_odd_headers'; even_and_odd: boolean }
  | { op: 'set_header'; section?: number; kind?: ChromeKind; with: string }
  | { op: 'set_footer'; section?: number; kind?: ChromeKind; with: string }
  | { op: 'clear_header'; section?: number; kind?: ChromeKind }
  | { op: 'clear_footer'; section?: number; kind?: ChromeKind }
  | { op: 'comment_add'; at: ParagraphAddress; select?: string; occurrence?: number; text: string }
  | { op: 'comment_reply'; comment_id: string; text: string }
  | { op: 'comment_set_status'; comment_id: string; status: 'open'|'resolved' }
  | { op: 'comment_delete'; comment_id: string }
  | { op: 'revision_settle'; target: string; action: 'accept'|'reject' };
export type CreateCommand = { kind: 'create'; paragraphs?: string[]; html?: string };
export type ReadCommand = { kind: 'read'; read_kind?: 'document'|'document_ui'|'styles'|'comments'|'revisions'|'assets'; view?: 'markup'|'final'|'original' };
export type FindCommand = { kind: 'find'; query: string; ignore_case?: boolean; view?: 'markup'|'final'|'original' };
export type EditCommand = { kind: 'edit'; author: string; change_mode: ChangeMode; op: EditOp };
export type Command = CreateCommand | ReadCommand | FindCommand | EditCommand;
export type CommandRequest = { command: Command; expected_source?: SourceHash };
export type Plan = { base: SourceHash; author: string; change_mode: ChangeMode; ops: [EditOp, ...EditOp[]] };
export type PlanRequest = { plan: Plan; preview_key?: string };
export type PlanParseResult = { outcome: 'parsed'; plan: Plan } | { outcome: 'rejected'; diagnostic: Diagnostic };
export type Request = { Command: CommandRequest } | { Plan: PlanRequest };
export type Span = { line: number; column: number; end_line?: number; end_column?: number };
export type Diagnostic = { code: string; message: string; path?: string; span?: Span };
export type OperationReport = { index: number; op: string; outcome: string; summary: string; affected?: unknown[]; context_truncated?: boolean };
export type PlanReport = { completed: number; stopped_at?: number; ops: OperationReport[]; repaired_ids: string[]; allocated_ids: string[]; aliases: Record<string, unknown> };
export type CommandResult = { outcome: 'completed'; source?: SourceHash; result?: unknown; bytes?: Uint8Array } | { outcome: 'rejected'; source?: SourceHash; result?: unknown; diagnostic: Diagnostic };
export type PlanResult = { outcome: 'previewed'; source: SourceHash; plan: Plan; canonical_toml: string; preview_key: string; report: PlanReport } | { outcome: 'committed'; source: SourceHash; plan: Plan; canonical_toml: string; report: PlanReport; bytes: Uint8Array } | { outcome: 'rejected'; source?: SourceHash; plan?: Plan; diagnostic: Diagnostic; report?: PlanReport };
export type RequestResult = CommandResult | PlanResult;
