#!/usr/bin/env python3
"""Generate the docxdriver REPL sandbox code from shared Pi templates (no Node)."""
import ast
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def template(path, name):
    text = path.read_text()
    match = re.search(r'export const ' + name + r'(?:\s*:\s*string)?\s*=\s*`((?:\\.|[^`])*)`;', text, re.S)
    if not match:
        raise ValueError(f'Missing template {name} in {path}')
    # The shared templates contain ordinary JavaScript string escapes, not interpolation.
    value = match[1]
    if '${' in value:
        raise ValueError('REPL prelude templates must not contain interpolation')
    escapes = {'n': '\n', 'r': '\r', 't': '\t', 'b': '\b', 'f': '\f', 'v': '\v', '0': '\0'}
    return re.sub(r'\\(.)', lambda m: escapes.get(m[1], m[1]), value, flags=re.S)


class AsyncHostCalls(ast.NodeTransformer):
    def visit_FunctionDef(self, node):
        calls = [call for call in ast.walk(node) if isinstance(call, ast.Call)
                 and isinstance(call.func, ast.Name) and call.func.id.startswith(('_docx_', '_quote_', '_term_', '_inline_'))]
        if not calls:
            return node
        node = self.generic_visit(node)
        return ast.copy_location(ast.AsyncFunctionDef(name=node.name, args=node.args, body=node.body,
            decorator_list=node.decorator_list, returns=node.returns, type_comment=node.type_comment), node)

    def visit_Call(self, node):
        node = self.generic_visit(node)
        if isinstance(node.func, ast.Name) and node.func.id.startswith(('_docx_', '_quote_', '_term_', '_inline_')):
            return ast.copy_location(ast.Await(value=node), node)
        return node


def generate():
    plan = ROOT / 'packages/docxdriver-pi/src/python-plan-prelude.ts'
    quote = ROOT / 'packages/docxdriver-pi/src/python-quote-prelude.ts'
    prelude = template(quote, 'QUOTE_PYTHON_PRELUDE') + '\n' + template(plan, 'PYTHON_PRELUDE')
    prelude = ast.unparse(ast.fix_missing_locations(AsyncHostCalls().visit(ast.parse(prelude))))
    reference = template(plan, 'PYTHON_API_REFERENCE') + '\n' + template(quote, 'QUOTE_API_REFERENCE')
    reference = re.sub(r'\b(docx_(?:read|find|create|review|commit|help)|quote_(?:find|validate|lint)|term_render|inline_validate)\(', r'await \1(', reference)
    reference = re.sub(r'await docx_read\(([^)\n]*)\)\.markup', r'(await docx_read(\1)).markup', reference)
    return '# Generated by scripts/generate-docxdriver-repl-prelude.py; edit the shared Pi templates.\nPRELUDE = ' + repr(prelude) + '\nREFERENCE = ' + repr(reference) + '\n'


if __name__ == '__main__':
    (ROOT / 'crates/docxdriver-python/python/docxdriver/repl/prelude.py').write_text(generate())
